<script>
	import "./main.css"
	export let data

	let buttonClick = false
	let postId = 0
	let newsId = 1
	let postData = data.posts[postId]

	$: {
		postData = data.posts[postId]
		newsId = postId + 1
	}
	const cssEffect = () => {
		buttonClick = true
		setTimeout(() => {
			buttonClick = false
		}, 1000)
	}
	const getPost = (p) => {
		cssEffect()
		if (p === 1) {
			postId < 98 ? (postId += 1) : ""
		} else {
			postId > 0 ? (postId -= 1) : ""
		}
	}

	const dateBatter = (date) => {
		const getDate = new Date(date)
		const bestDate = getDate.toLocaleString()
		return bestDate
	}
</script>

<div class="flex flex-col items-center h-full">
	<!-- start code for header section -->
	<div
		class="bg-blue-600 w-full text-center py-1 font-semibold text-white flex justify-center items-center"
	>
		<img class="w-auto h-7 pr-1" src="/favicon.png" alt="" />
		<h2 class=" first-letter:text-2xl first-letter:text-yellow-300">Dholpur 99</h2>
	</div>
	<!-- start code for news section -->
	<!-- This is an example component -->
	<div class="max-w-2xl flex-1 mx-2 my-6" class:shake-horizontal={buttonClick}>
		<div
			class="shadow-md border rounded-lg max-w-sm bg-gray-800 border-gray-700 flex flex-col justify-between flex-1 h-full"
		>
			{#if postData?.imageUrl}
				<img class="rounded-t-lg w-full h-full max-h-56" src={postData.imageUrl} alt="" />
			{:else}
				<img
					class="rounded-t-lg w-full h-[218px]"
					src="https://i.imgur.com/5a1hTxW.jpeg"
					alt=""
				/>
			{/if}
			<div class="px-2 py-1 flex items-center justify-between text-xs">
				<p>Newsid:{newsId}</p>
				<p>Date:{dateBatter(postData.publishTime)}</p>
			</div>
			<div class="pt-4 px-2">
				<h5 class="font-bold text-base tracking-tight mb-2 text-white">
					{postData.title} - {newsId}
				</h5>
			</div>
			<div class="p-2">
				<p class="font-normal mb-3 text-gray-400 text-xs">
					{postData.bodyText}
				</p>
			</div>
			<div class="flex justify-between px-2 mb-3">
				<button
					on:click={() => getPost(0)}
					class="text-white bg-blue-700 hover:bg-blue-800 font-medium rounded-lg text-sm px-3 py-2 text-center inline-flex items-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
				>
					<svg
						xmlns="http://www.w3.org/2000/svg"
						fill="none"
						viewBox="0 0 24 24"
						stroke-width="1.5"
						stroke="currentColor"
						class="mr-2 h-4 w-4"
					>
						<path
							stroke-linecap="round"
							stroke-linejoin="round"
							d="M19.5 12h-15m0 0l6.75 6.75M4.5 12l6.75-6.75"
						/>
					</svg>
					Prev
				</button>
				<button
					on:click={() => getPost(1)}
					class="text-white bg-blue-700 hover:bg-blue-800 font-medium rounded-lg text-sm px-3 py-2 text-center inline-flex items-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
				>
					Next
					<svg
						xmlns="http://www.w3.org/2000/svg"
						fill="none"
						viewBox="0 0 24 24"
						stroke-width="1.5"
						stroke="currentColor"
						class="ml-2 h-4 w-4"
					>
						<path
							stroke-linecap="round"
							stroke-linejoin="round"
							d="M4.5 12h15m0 0l-6.75-6.75M19.5 12l-6.75 6.75"
						/>
					</svg>
				</button>
			</div>
		</div>
	</div>
</div>

<style>
	.shake-horizontal {
		-webkit-animation: shake-horizontal 0.8s cubic-bezier(0.455, 0.03, 0.515, 0.955) both;
		animation: shake-horizontal 0.8s cubic-bezier(0.455, 0.03, 0.515, 0.955) both;
	}

	/* ----------------------------------------------
 * Generated by Animista on 2023-12-2 14:19:35
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

	/**
 * ----------------------------------------
 * animation shake-horizontal
 * ----------------------------------------
 */
	@-webkit-keyframes shake-horizontal {
		0%,
		100% {
			-webkit-transform: translateX(0);
			transform: translateX(0);
		}
		10%,
		30%,
		50%,
		70% {
			-webkit-transform: translateX(-10px);
			transform: translateX(-10px);
		}
		20%,
		40%,
		60% {
			-webkit-transform: translateX(10px);
			transform: translateX(10px);
		}
		80% {
			-webkit-transform: translateX(8px);
			transform: translateX(8px);
		}
		90% {
			-webkit-transform: translateX(-8px);
			transform: translateX(-8px);
		}
	}
	@keyframes shake-horizontal {
		0%,
		100% {
			-webkit-transform: translateX(0);
			transform: translateX(0);
		}
		10%,
		30%,
		50%,
		70% {
			-webkit-transform: translateX(-10px);
			transform: translateX(-10px);
		}
		20%,
		40%,
		60% {
			-webkit-transform: translateX(10px);
			transform: translateX(10px);
		}
		80% {
			-webkit-transform: translateX(8px);
			transform: translateX(8px);
		}
		90% {
			-webkit-transform: translateX(-8px);
			transform: translateX(-8px);
		}
	}
</style>
